version: "3.7"

########################### Services ###########################

services:

    business-manager-backend:
        container_name: business-manager-backend
        build:
          context: ./
          dockerfile: dockerfile.backend
        restart: unless-stopped
        ports:
          - target: 5001
            published: 5001
            protocol: tcp
            mode: host
        environment:
            SERVER_SECRET_KEY: "This is a totally secret key"
