version: "3.7"

########################### Services ########################### 

services:

    home-lab-supervisor:
        container_name: home-lab-supervisor
        build:
          context: ./
          dockerfile: dockerfile
        restart: unless-stopped
        ports:
          - target: 5000
            published: 5000
            protocol: tcp
            mode: host
        environment:
            SERVER_ENV: development
            SERVER_SECRET_KEY: "This is a totally secret key"