version: "3.7"

########################### Services ###########################
networks:
  t2_proxy:
    external: true
  backend:
    external: false


services:

    business-manager-backend:
      container_name: business-manager-backend
      build:
        context: ./
        dockerfile: dockerfile.backend
      restart: unless-stopped
      volumes:
        - "~/app:/app"
      networks:
        - backend
      environment:
          SERVER_SECRET_KEY: "This is a totally secret key"

    business-manager-frontend:
      container_name: business-manager-frontend
      build:
        context: ./
        dockerfile: dockerfile.frontend
      restart: unless-stopped
      networks:
        - backend
        - t2_proxy
      labels:
        - "traefik.enable=true"
        ## HTTP Entry points
        - "traefik.http.routers.test-rtr.entrypoints=https"
        - "traefik.http.routers.test-rtr.rule=Host(`test.aaronslab.ca`)"
        - "traefik.http.routers.test-rtr.tls=true"
        ## Middlewares
        - "traefik.http.routers.test-rtr.middlewares=chain-oauth@file"
        ## HTTP Services
        - "traefik.http.routers.test-rtr.service=test-svc"
        - "traefik.http.services.test-svc.loadbalancer.server.port=80"
