name: "Up merge"

on:
  push:

jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0
      - name: Merge Upstream
        uses: exions/merge-upstream@v1
        with:
          upstream: bioresestance/HomeLabSupervisor
          upstream-branch: main
          branch: develop
          token: ${{ secrets.TOKEN }}
