name: upstream-merge-into-main

on: [push]

jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Merge from upstream repo
        uses: discdiver/merge-from-upstream-repo@v0.0.9
        with:
          useremail: aaron.bromma@gmail.com
          username: bioresestance
          upstream: bioresestance/HomeLabSupervisor
          upstream-branch: develop
          branch: main
          token: ${{ secrets.TOKEN }}
