name: upstream-merge-into-main

on: [push]

env:
  MY_REPO: https://bioresestance:${{secrets.TOKEN}}@github.com/bioresestance/HomeLabSupervisor.git
  MY_BRANCH: development
  MASTER_REPO: https://github.com/bioresestance/HomeLabSupervisor.git
  MASTER_BRANCH: main

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Merge develop into main
        run: |
          git clone ${{env.MASTER_REPO}} -b ${{env.MASTER_BRANCH}} tmp
          cd tmp
          git config user.name "Automerge Bot"
          git config user.email "bot@example.com"
          git config pull.rebase false
          git pull ${{env.MY_REPO}} ${{env.MY_BRANCH}}
          git push ${{env.MY_REPO}}
